language: elixir

elixir:
  - '1.5'
otp_release: '20.0'

matrix:
  include:
    - elixir: '1.4'
      otp_release: '18.0'
    - elixir: '1.4'
      otp_release: '19.0'
    - elixir: '1.4'
      otp_release: '20.0'
    - elixir: '1.5'
      otp_release: '18.0'
    - elixir: '1.5'
      otp_release: '19.0'
